ADMIN_USERNAME = (ENV['ADMIN_USERNAME'] or 'admin')
ADMIN_PASSWORD = (ENV['ADMIN_PASSWORD'] or 'passw0rd')

LAST_FM_USERNAME = 'sitoto'
LAST_FM_API_KEY = (ENV['LAST_FM_API_KEY'] or 'b25b959554ed76058ac220b7b2e0a026')
LAST_FM_API_SECRET = (ENV['LAST_FM_API_SECRET'] or nil)

TWITTER_ANYWHERE_API_KEY = 'ZUgEyEcINKMBQNJzqcfMiw'

GOOGLE_ANALYTICS_KEY = 'UA-27922932-1'
OBSERVER_APP_KEY = 'agtvYnNlcnZlcmFwcHINCxIEU2l0ZRjkyvUBDA'

CLOUDAPP_USERNAME = ENV['CLOUDAPP_USERNAME']
CLOUDAPP_PASSWORD = ENV['CLOUDAPP_PASSWORD']

WEIBO_QQ_URL0 = 'http://t.qq.com/online_web'
WEIBO_QQ_URL = 'http://t.qq.com/sitoto'
