defaults: &defaults
  options:
    identity_map_enabled: true


development:
  host: localhost
  database: mcai_development
#  identity_map_enabled: true

test:
  host: localhost
  database: mcai_test

# set these environment variables on your prod server
production:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: tuoshuiba

# set these environment variables on your prod server
# production:
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
