require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NovelsController do

  # This should return the minimal set of attributes required to create a valid
  # Novel. As you add validations to Novel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NovelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all novels as @novels" do
      novel = Novel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:novels).should eq([novel])
    end
  end

  describe "GET show" do
    it "assigns the requested novel as @novel" do
      novel = Novel.create! valid_attributes
      get :show, {:id => novel.to_param}, valid_session
      assigns(:novel).should eq(novel)
    end
  end

  describe "GET new" do
    it "assigns a new novel as @novel" do
      get :new, {}, valid_session
      assigns(:novel).should be_a_new(Novel)
    end
  end

  describe "GET edit" do
    it "assigns the requested novel as @novel" do
      novel = Novel.create! valid_attributes
      get :edit, {:id => novel.to_param}, valid_session
      assigns(:novel).should eq(novel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Novel" do
        expect {
          post :create, {:novel => valid_attributes}, valid_session
        }.to change(Novel, :count).by(1)
      end

      it "assigns a newly created novel as @novel" do
        post :create, {:novel => valid_attributes}, valid_session
        assigns(:novel).should be_a(Novel)
        assigns(:novel).should be_persisted
      end

      it "redirects to the created novel" do
        post :create, {:novel => valid_attributes}, valid_session
        response.should redirect_to(Novel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved novel as @novel" do
        # Trigger the behavior that occurs when invalid params are submitted
        Novel.any_instance.stub(:save).and_return(false)
        post :create, {:novel => { "name" => "invalid value" }}, valid_session
        assigns(:novel).should be_a_new(Novel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Novel.any_instance.stub(:save).and_return(false)
        post :create, {:novel => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested novel" do
        novel = Novel.create! valid_attributes
        # Assuming there are no other novels in the database, this
        # specifies that the Novel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Novel.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => novel.to_param, :novel => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested novel as @novel" do
        novel = Novel.create! valid_attributes
        put :update, {:id => novel.to_param, :novel => valid_attributes}, valid_session
        assigns(:novel).should eq(novel)
      end

      it "redirects to the novel" do
        novel = Novel.create! valid_attributes
        put :update, {:id => novel.to_param, :novel => valid_attributes}, valid_session
        response.should redirect_to(novel)
      end
    end

    describe "with invalid params" do
      it "assigns the novel as @novel" do
        novel = Novel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Novel.any_instance.stub(:save).and_return(false)
        put :update, {:id => novel.to_param, :novel => { "name" => "invalid value" }}, valid_session
        assigns(:novel).should eq(novel)
      end

      it "re-renders the 'edit' template" do
        novel = Novel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Novel.any_instance.stub(:save).and_return(false)
        put :update, {:id => novel.to_param, :novel => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested novel" do
      novel = Novel.create! valid_attributes
      expect {
        delete :destroy, {:id => novel.to_param}, valid_session
      }.to change(Novel, :count).by(-1)
    end

    it "redirects to the novels list" do
      novel = Novel.create! valid_attributes
      delete :destroy, {:id => novel.to_param}, valid_session
      response.should redirect_to(novels_url)
    end
  end

end
