require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WeixinsController do

  # This should return the minimal set of attributes required to create a valid
  # Weixin. As you add validations to Weixin, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WeixinsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all weixins as @weixins" do
      weixin = Weixin.create! valid_attributes
      get :index, {}, valid_session
      assigns(:weixins).should eq([weixin])
    end
  end

  describe "GET show" do
    it "assigns the requested weixin as @weixin" do
      weixin = Weixin.create! valid_attributes
      get :show, {:id => weixin.to_param}, valid_session
      assigns(:weixin).should eq(weixin)
    end
  end

  describe "GET new" do
    it "assigns a new weixin as @weixin" do
      get :new, {}, valid_session
      assigns(:weixin).should be_a_new(Weixin)
    end
  end

  describe "GET edit" do
    it "assigns the requested weixin as @weixin" do
      weixin = Weixin.create! valid_attributes
      get :edit, {:id => weixin.to_param}, valid_session
      assigns(:weixin).should eq(weixin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Weixin" do
        expect {
          post :create, {:weixin => valid_attributes}, valid_session
        }.to change(Weixin, :count).by(1)
      end

      it "assigns a newly created weixin as @weixin" do
        post :create, {:weixin => valid_attributes}, valid_session
        assigns(:weixin).should be_a(Weixin)
        assigns(:weixin).should be_persisted
      end

      it "redirects to the created weixin" do
        post :create, {:weixin => valid_attributes}, valid_session
        response.should redirect_to(Weixin.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved weixin as @weixin" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weixin.any_instance.stub(:save).and_return(false)
        post :create, {:weixin => { "name" => "invalid value" }}, valid_session
        assigns(:weixin).should be_a_new(Weixin)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weixin.any_instance.stub(:save).and_return(false)
        post :create, {:weixin => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested weixin" do
        weixin = Weixin.create! valid_attributes
        # Assuming there are no other weixins in the database, this
        # specifies that the Weixin created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Weixin.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => weixin.to_param, :weixin => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested weixin as @weixin" do
        weixin = Weixin.create! valid_attributes
        put :update, {:id => weixin.to_param, :weixin => valid_attributes}, valid_session
        assigns(:weixin).should eq(weixin)
      end

      it "redirects to the weixin" do
        weixin = Weixin.create! valid_attributes
        put :update, {:id => weixin.to_param, :weixin => valid_attributes}, valid_session
        response.should redirect_to(weixin)
      end
    end

    describe "with invalid params" do
      it "assigns the weixin as @weixin" do
        weixin = Weixin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weixin.any_instance.stub(:save).and_return(false)
        put :update, {:id => weixin.to_param, :weixin => { "name" => "invalid value" }}, valid_session
        assigns(:weixin).should eq(weixin)
      end

      it "re-renders the 'edit' template" do
        weixin = Weixin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weixin.any_instance.stub(:save).and_return(false)
        put :update, {:id => weixin.to_param, :weixin => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested weixin" do
      weixin = Weixin.create! valid_attributes
      expect {
        delete :destroy, {:id => weixin.to_param}, valid_session
      }.to change(Weixin, :count).by(-1)
    end

    it "redirects to the weixins list" do
      weixin = Weixin.create! valid_attributes
      delete :destroy, {:id => weixin.to_param}, valid_session
      response.should redirect_to(weixins_url)
    end
  end

end
